# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 11:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Spareparts_Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL),
        ),
    ]
