# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spareparts_Shop', '0002_auto_20180228_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='description',
            field=models.TextField(default=True, max_length=4000),
        ),
    ]
